### ISSUE TITLE
kantts/bin/text_to_wav.py 加载SambertHifigan语音合成-中文-多人预训练-16k 合成音频报错

### ISSUE THREAD

**Issue by airstillblue** [AlibabaResearch/KAN-TTS#65]
**报错信息**
Converting text to symbols...
Traceback (most recent call last):
  File "./kantts/bin/text_to_wav.py", line 168, in <module>
    text_to_wav(
  File "./kantts/bin/text_to_wav.py", line 102, in text_to_wav
    speaker = config["linguistic_unit"]["speaker_list"].split(",")[0]
KeyError: 'linguistic_unit'

**运行角本**
#!/bin/bash
# SambertHifigan语音合成-中文-多人预训练-16k
# speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k

outdir=out
[ -d $outdir ] && rm -rf $outdir; mkdir -p $outdir

python ./kantts/bin/text_to_wav.py \
  --txt ./test_data/txt \
  --output_dir $outdir \
  --res_zip ../funtts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/resource.zip \
  --am_ckpt ../funtts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/basemodel_16k/hifigan/ckpt/checkpoint_2000000.pth \
  --voc_ckpt ../funtts/speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/basemodel_16k/hifigan/ckpt/checkpoint_2000000.pth 

**运行环境 linux**
conda list 
# packages in environment at /home/eeodev/anaconda3/envs/funtts:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   1.4.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.13.36                  pypi_0    pypi
aliyun-python-sdk-kms     2.16.1                   pypi_0    pypi
aniso8601                 9.0.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
audioread                 3.0.0                    pypi_0    pypi
autopep8                  2.0.2                    pypi_0    pypi
bitstring                 4.0.2                    pypi_0    pypi
ca-certificates           2023.05.30           h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cfgv                      3.3.1                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cmake                     3.26.4                   pypi_0    pypi
coloredlogs               14.0                     pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              41.0.1                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.35                  pypi_0    pypi
datasets                  2.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
distance                  0.1.3                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
dnspython                 2.3.0                    pypi_0    pypi
easyasr                   0.0.7                    pypi_0    pypi
edit-distance             1.0.6                    pypi_0    pypi
editdistance              0.5.2                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
espnet-tts-frontend       0.0.3                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
eventlet                  0.33.3                   pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
flask                     2.1.3                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flask-restful             0.3.10                   pypi_0    pypi
flask-socketio            4.3.2                    pypi_0    pypi
flask-talisman            1.0.0                    pypi_0    pypi
fonttools                 4.40.0                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
funasr                    0.6.1                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
g2p                       1.1.20230511             pypi_0    pypi
g2p-en                    2.1.0                    pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
greenlet                  2.0.2                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
huggingface-hub           0.15.1                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hyperpyyaml               1.2.1                    pypi_0    pypi
identify                  2.5.24                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
inflect                   6.0.4                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaconv                    0.3.4                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
kaldiio                   2.18.0                   pypi_0    pypi
kantts                    0.0.1                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kwsbp                     0.0.6                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.4.4                h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
librosa                   0.9.2                    pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lit                       16.0.5.post0             pypi_0    pypi
llvmlite                  0.40.1rc1                pypi_0    pypi
lxml                      4.9.2                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mindaec                   0.0.2                    pypi_0    pypi
mir-eval                  0.7                      pypi_0    pypi
modelscope                1.6.1                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.5                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  2.8.4                    pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
nodeenv                   1.8.0                    pypi_0    pypi
numba                     0.57.0                   pypi_0    pypi
numpy                     1.22.0                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openpyxl                  3.1.2                    pypi_0    pypi
openssl                   3.0.8                h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
oss2                      2.18.0                   pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
panphon                   0.20.0                   pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1.2           py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
platformdirs              3.5.3                    pypi_0    pypi
pooch                     1.7.0                    pypi_0    pypi
pre-commit                3.3.3                    pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  3.20.0                   pypi_0    pypi
ptflops                   0.7                      pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py-sound-connect          0.2.1                    pypi_0    pypi
pyarrow                   12.0.1                   pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.18.0                   pypi_0    pypi
pydantic                  1.10.9                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pypinyin                  0.44.0                   pypi_0    pypi
pysptk                    0.1.21                   pypi_0    pypi
python                    3.8.16               h955ad1f_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
python-engineio           3.14.2                   pypi_0    pypi
python-socketio           4.6.1                    pypi_0    pypi
pytorch-wavelets          1.3.0                    pypi_0    pypi
pytorch-wpe               0.0.1                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
resampy                   0.4.2                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rotary-embedding-torch    0.2.3                    pypi_0    pypi
ruamel-yaml               0.17.28                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                67.8.0           py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
simplejson                3.19.1                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
sox                       1.4.1                    pypi_0    pypi
speechbrain               0.5.14                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sympy                     1.12                     pypi_0    pypi
tensorboard               1.15.0                   pypi_0    pypi
tensorboardx              2.6                      pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
textgrid                  1.5                      pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tomli                     2.0.1                    pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torch-complex             0.4.3                    pypi_0    pypi
torchaudio                2.0.2                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
ttsfrd                    0.2.1                    pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         4.6.3                    pypi_0    pypi
unicodecsv                0.14.1                   pypi_0    pypi
unidecode                 1.3.6                    pypi_0    pypi
urllib3                   2.0.3                    pypi_0    pypi
virtualenv                20.23.0                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yapf                      0.40.0                   pypi_0    pypi
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by GinChow** [comment]
it seems you specified the wrong `am_ckpt` path,  acoustic model locates in the folder `basemodel_16k/sambert/`.
