### ISSUE TITLE
Sambert微调声学模型失败RuntimeError: Error(s) in loading state_dict for KanTtsSAMBERT:         size mismatch for spk_tokenizer.weight: copying a param with shape torch.Size([9, 32]) from checkpoint, the shape in current model is torch.Size([10, 32]).

### ISSUE THREAD

**Issue by kingki663** [AlibabaResearch/KAN-TTS#91]
当我使用命令`conda env create -f environment.yaml`创建虚拟环境并准备好数据后，由于我是用的显卡为4060不支持低版本的运算架构然后我执行`pip install --upgrade torch`进行升级，然后继续执行`CUDA_VISIBLE_DEVICES=0 python kantts/bin/train_sambert.py --model_config speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/basemodel_16k/sambert/config.yaml --resume_path speech_sambert-hifigan_tts_zh-cn_multisp_pretrain_16k/basemodel_16k/sambert/ckpt/checkpoint_980000.pth --root_dir training_stage/SSB0009_feats --stage_dir training_stage/SSB0009_sambert_ckpt`时报错如下：

RuntimeError: Error(s) in loading state_dict for KanTtsSAMBERT:
        size mismatch for spk_tokenizer.weight: copying a param with shape torch.Size([9, 32]) from checkpoint, the shape in current model is torch.Size([10, 32]).

我想知道这是什么原因引起的

**Comment by kingki663** [comment]
已解决，出错原因：`config.yaml`文件填写错误

**Comment by kingki663** [comment]
已解决，出错原因：`config.yaml`文件填写错误

**Comment by kangle0224** [comment]
请问怎么解决的？具体需要改哪里？

**Comment by Wanqingling** [comment]
你好，请问怎么解决的，具体需要改哪里？我也遇到了相同的问题
